language : node_js
node_js :
 - stable
install:
 - npm install
 - npm install @material-ui/core@3.8.3 @material-ui/icons@3.0.2 @types/react @types/react-dom react react-dom
script:
 - npm run lint
 - npm run test-ci

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
